# Generated by Django 5.2.6 on 2025-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_blogpost_published_date_project_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position_rank',
            field=models.PositiveIntegerField(default=99, help_text='Lower number = higher seniority (e.g., 1 for President)'),
        ),
    ]
